package com.tp.venus.module.user.dao;

import android.database.sqlite.SQLiteDatabase;

import com.tp.venus.base.dao.NAbstractDaoSession;
import com.tp.venus.module.user.bean.User;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class UserDaoSession extends NAbstractDaoSession {

    private final DaoConfig baiduDaoConfig;

    private final UserDao mUserDao;

    public UserDaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        baiduDaoConfig = daoConfigMap.get(UserDao.class).clone();
        baiduDaoConfig.initIdentityScope(type);

        mUserDao = new UserDao(baiduDaoConfig, this);
        registerDao(User.class, mUserDao);
    }
    
    public void clear() {
        baiduDaoConfig.getIdentityScope().clear();
    }

    @Override
    protected AbstractDao<User, String> getDao() {
        return mUserDao;
    }
}
